import { localeMeta, type Locale } from './i18n-locales.ts';

export const COPY_KEYS = ['preview', 'previewBody', 'referencePrice', 'vatIncluded', 'featured', 'shelf', 'more', 'shown', 'reset', 'addToList', 'listAdded', 'selection', 'category', 'pendingSale', 'homeDescription'] as const;
export type CopyKey = (typeof COPY_KEYS)[number];

/** Each row follows COPY_KEYS. Tests enforce complete locale and interpolation parity. */
export const STOREFRONT_COPY: Record<Locale, readonly string[]> = {
  tr: ['Katalog önizlemesi', 'Çevrim içi ödeme kapalı. Ürün ayrıntıları için bize yazın.', 'Kaynak listedeki fiyat', 'KDV dahil', 'Öne çıkanlar', 'Raf', 'Daha fazla ürün', '{shown} / {total} ürün gösteriliyor', 'Filtreleri temizle', 'Listeme ekle', 'Listenize eklendi', 'Listem', 'Kategori', 'Bu ürünün satış bilgileri henüz doğrulanmadı.', 'Sirke, lokum, bal, sabun ve baharat. Taha’nın Gümülcine’deki aktarından, kendi hazırladıkları ve seçtikleri.'],
  el: ['Προεπισκόπηση καταλόγου', 'Οι ηλεκτρονικές πληρωμές δεν είναι ακόμη διαθέσιμες. Επικοινωνήστε μαζί μας για πληροφορίες προϊόντων.', 'Τιμή του αρχικού καταλόγου', 'Με ΦΠΑ', 'Επιλεγμένα προϊόντα', 'Συλλογή', 'Περισσότερα προϊόντα', 'Εμφανίζονται {shown} από {total} προϊόντα', 'Καθαρισμός φίλτρων', 'Προσθήκη στη λίστα μου', 'Προστέθηκε στη λίστα σας', 'Η λίστα μου', 'Κατηγορία', 'Τα στοιχεία πώλησης αυτού του προϊόντος δεν έχουν ακόμη επιβεβαιωθεί.', 'Ξίδι, λουκούμια, μέλι, σαπούνια και μπαχαρικά. Όσα παρασκευάζει και όσα επιλέγει ο Τάχα για το μαγαζί του στην Κομοτηνή.'],
  en: ['Catalogue preview', 'Online payment is not open yet. Contact us for product details.', 'Source catalogue price', 'VAT included', 'Featured selection', 'Shelf', 'More products', 'Showing {shown} of {total} products', 'Clear filters', 'Add to my list', 'Added to your list', 'My list', 'Category', 'The sales information for this product has not been verified yet.', 'Vinegar, lokum, honey, soap and spices. What Taha prepares and selects for his shop in Komotini.'],
  de: ['Katalogvorschau', 'Onlinezahlungen sind noch nicht verfügbar. Fragen zu Produkten beantworten wir persönlich.', 'Preis aus der ursprünglichen Liste', 'Inklusive MwSt.', 'Unsere Auswahl', 'Sortiment', 'Weitere Produkte', '{shown} von {total} Produkten', 'Filter zurücksetzen', 'Auf meine Liste', 'Zu Ihrer Liste hinzugefügt', 'Meine Liste', 'Kategorie', 'Die Verkaufsangaben zu diesem Produkt sind noch nicht bestätigt.', 'Essig, Lokum, Honig, Seife und Gewürze. Was Taha für seinen Laden in Komotini selbst zubereitet und auswählt.'],
  fr: ['Aperçu du catalogue', 'Le paiement en ligne n’est pas encore ouvert. Contactez-nous pour les détails des produits.', 'Prix du catalogue source', 'TVA comprise', 'Notre sélection', 'Rayon', 'Voir plus de produits', '{shown} produits affichés sur {total}', 'Effacer les filtres', 'Ajouter à ma liste', 'Ajouté à votre liste', 'Ma liste', 'Catégorie', 'Les informations de vente de ce produit ne sont pas encore vérifiées.', 'Vinaigre, loukoums, miel, savons et épices. Ce que Taha prépare et choisit pour sa boutique à Komotini.'],
  it: ['Anteprima del catalogo', 'Il pagamento online non è ancora disponibile. Contattateci per i dettagli dei prodotti.', 'Prezzo del catalogo originale', 'IVA inclusa', 'La nostra selezione', 'Reparto', 'Altri prodotti', '{shown} prodotti su {total}', 'Rimuovi i filtri', 'Aggiungi alla mia lista', 'Aggiunto alla tua lista', 'La mia lista', 'Categoria', 'Le informazioni di vendita di questo prodotto non sono ancora verificate.', 'Aceto, lokum, miele, saponi e spezie. Quello che Taha prepara e seleziona per la sua bottega a Komotini.'],
  es: ['Vista previa del catálogo', 'El pago en línea aún no está disponible. Contacta con nosotros para conocer los detalles de los productos.', 'Precio del catálogo original', 'IVA incluido', 'Nuestra selección', 'Sección', 'Más productos', 'Mostrando {shown} de {total} productos', 'Borrar filtros', 'Añadir a mi lista', 'Añadido a tu lista', 'Mi lista', 'Categoría', 'La información de venta de este producto aún no se ha verificado.', 'Vinagre, lokum, miel, jabones y especias. Lo que Taha prepara y elige para su tienda en Komotini.'],
  nl: ['Catalogusvoorbeeld', 'Online betalen is nog niet mogelijk. Neem contact op voor productinformatie.', 'Prijs uit de oorspronkelijke lijst', 'Inclusief btw', 'Onze selectie', 'Assortiment', 'Meer producten', '{shown} van {total} producten getoond', 'Filters wissen', 'Aan mijn lijst toevoegen', 'Aan uw lijst toegevoegd', 'Mijn lijst', 'Categorie', 'De verkoopgegevens van dit product zijn nog niet gecontroleerd.', 'Azijn, lokum, honing, zeep en specerijen. Wat Taha zelf maakt en uitkiest voor zijn winkel in Komotini.'],
  pl: ['Podgląd katalogu', 'Płatności online nie są jeszcze dostępne. Skontaktuj się z nami w sprawie produktów.', 'Cena z katalogu źródłowego', 'Z VAT', 'Wybrane produkty', 'Dział', 'Więcej produktów', 'Wyświetlono {shown} z {total} produktów', 'Wyczyść filtry', 'Dodaj do mojej listy', 'Dodano do Twojej listy', 'Moja lista', 'Kategoria', 'Informacje dotyczące sprzedaży tego produktu nie zostały jeszcze zweryfikowane.', 'Ocet, lokum, miód, mydła i przyprawy. Produkty, które Taha przygotowuje i wybiera do swojego sklepu w Komotini.'],
  no: ['Forhåndsvisning av katalogen', 'Nettbetaling er ikke tilgjengelig ennå. Kontakt oss for produktinformasjon.', 'Pris fra den opprinnelige listen', 'Inkludert mva.', 'Utvalgte produkter', 'Utvalg', 'Flere produkter', 'Viser {shown} av {total} produkter', 'Nullstill filtre', 'Legg til i listen min', 'Lagt til i listen din', 'Min liste', 'Kategori', 'Salgsopplysningene for dette produktet er ennå ikke bekreftet.', 'Eddik, lokum, honning, såpe og krydder. Det Taha lager og velger ut til butikken sin i Komotini.'],
  bg: ['Преглед на каталога', 'Онлайн плащането все още не е достъпно. Свържете се с нас за информация за продуктите.', 'Цена от първоначалния каталог', 'С включен ДДС', 'Подбрани продукти', 'Асортимент', 'Още продукти', 'Показани са {shown} от {total} продукта', 'Изчисти филтрите', 'Добави в моя списък', 'Добавено в списъка ви', 'Моят списък', 'Категория', 'Данните за продажба на този продукт все още не са потвърдени.', 'Оцет, локум, мед, сапуни и подправки. Това, което Таха приготвя и подбира за магазина си в Комотини.'],
  ro: ['Previzualizarea catalogului', 'Plata online nu este încă disponibilă. Contactați-ne pentru detalii despre produse.', 'Preț din catalogul original', 'TVA inclus', 'Produse alese', 'Raion', 'Mai multe produse', 'Sunt afișate {shown} din {total} produse', 'Șterge filtrele', 'Adaugă în lista mea', 'Adăugat în lista dumneavoastră', 'Lista mea', 'Categorie', 'Informațiile de vânzare ale acestui produs nu au fost încă verificate.', 'Oțet, rahat, miere, săpunuri și condimente. Ceea ce Taha pregătește și alege pentru magazinul său din Komotini.'],
  sv: ['Förhandsvisning av katalogen', 'Onlinebetalning är ännu inte tillgänglig. Kontakta oss för produktinformation.', 'Pris från den ursprungliga listan', 'Inklusive moms', 'Utvalda produkter', 'Sortiment', 'Fler produkter', 'Visar {shown} av {total} produkter', 'Rensa filter', 'Lägg till i min lista', 'Tillagd i din lista', 'Min lista', 'Kategori', 'Försäljningsuppgifterna för denna produkt har ännu inte verifierats.', 'Vinäger, lokum, honung, tvål och kryddor. Det Taha tillverkar och väljer ut till sin butik i Komotini.'],
  da: ['Forhåndsvisning af kataloget', 'Onlinebetaling er endnu ikke tilgængelig. Kontakt os for produktinformation.', 'Pris fra den oprindelige liste', 'Inklusive moms', 'Udvalgte produkter', 'Sortiment', 'Flere produkter', 'Viser {shown} af {total} produkter', 'Nulstil filtre', 'Føj til min liste', 'Føjet til din liste', 'Min liste', 'Kategori', 'Salgsoplysningerne for dette produkt er endnu ikke bekræftet.', 'Eddike, lokum, honning, sæbe og krydderier. Det Taha fremstiller og udvælger til sin butik i Komotini.'],
  fi: ['Luettelon esikatselu', 'Verkkomaksaminen ei ole vielä käytettävissä. Kysy meiltä lisätietoja tuotteista.', 'Alkuperäisen luettelon hinta', 'Sisältää alv:n', 'Valikoituja tuotteita', 'Valikoima', 'Lisää tuotteita', 'Näytetään {shown} tuotetta yhteensä {total} tuotteesta', 'Tyhjennä suodattimet', 'Lisää listalleni', 'Lisätty listallesi', 'Oma lista', 'Tuoteryhmä', 'Tämän tuotteen myyntitietoja ei ole vielä vahvistettu.', 'Etikkaa, lokumia, hunajaa, saippuaa ja mausteita. Tahan valmistamia ja valitsemia tuotteita hänen liikkeestään Komotinissa.'],
  pt: ['Pré-visualização do catálogo', 'O pagamento online ainda não está disponível. Contacte-nos para obter informações sobre os produtos.', 'Preço do catálogo original', 'IVA incluído', 'A nossa seleção', 'Secção', 'Mais produtos', 'A mostrar {shown} de {total} produtos', 'Limpar filtros', 'Adicionar à minha lista', 'Adicionado à sua lista', 'A minha lista', 'Categoria', 'As informações de venda deste produto ainda não foram verificadas.', 'Vinagre, lokum, mel, sabonetes e especiarias. O que Taha prepara e escolhe para a sua loja em Komotini.'],
  hu: ['Katalógus-előnézet', 'Az online fizetés még nem érhető el. A termékekről érdeklődjön nálunk.', 'Az eredeti katalógus ára', 'Áfával együtt', 'Válogatott termékek', 'Kínálat', 'További termékek', '{shown} termék megjelenítve, összesen {total}', 'Szűrők törlése', 'Hozzáadás a listámhoz', 'Hozzáadva a listájához', 'Saját listám', 'Kategória', 'A termék értékesítési adatait még nem ellenőriztük.', 'Ecet, lokum, méz, szappanok és fűszerek. Amit Taha maga készít és kiválaszt komotini üzletébe.'],
  cs: ['Náhled katalogu', 'Online platby zatím nejsou dostupné. Podrobnosti o produktech vám rádi sdělíme.', 'Cena z původního katalogu', 'Včetně DPH', 'Vybrané produkty', 'Sortiment', 'Další produkty', 'Zobrazeno {shown} z {total} produktů', 'Vymazat filtry', 'Přidat na můj seznam', 'Přidáno na váš seznam', 'Můj seznam', 'Kategorie', 'Prodejní údaje tohoto produktu zatím nebyly ověřeny.', 'Ocet, lokum, med, mýdla a koření. Co Taha připravuje a vybírá pro svůj obchod v Komotini.'],
  hr: ['Pregled kataloga', 'Plaćanje putem interneta još nije dostupno. Javite nam se za pojedinosti o proizvodima.', 'Cijena iz izvornog kataloga', 'PDV uključen', 'Odabrani proizvodi', 'Ponuda', 'Više proizvoda', 'Prikazano {shown} od {total} proizvoda', 'Ukloni filtre', 'Dodaj na moj popis', 'Dodano na vaš popis', 'Moj popis', 'Kategorija', 'Prodajni podaci za ovaj proizvod još nisu potvrđeni.', 'Ocat, lokum, med, sapuni i začini. Ono što Taha priprema i bira za svoju trgovinu u Komotiniju.'],
  sk: ['Náhľad katalógu', 'Online platby zatiaľ nie sú dostupné. Podrobnosti o produktoch vám radi poskytneme.', 'Cena z pôvodného katalógu', 'Vrátane DPH', 'Vybrané produkty', 'Sortiment', 'Ďalšie produkty', 'Zobrazených {shown} z {total} produktov', 'Vymazať filtre', 'Pridať na môj zoznam', 'Pridané na váš zoznam', 'Môj zoznam', 'Kategória', 'Predajné údaje tohto produktu zatiaľ neboli overené.', 'Ocot, lokum, med, mydlá a koreniny. Čo Taha pripravuje a vyberá pre svoj obchod v Komotini.'],
};

export function ux(locale: Locale, key: CopyKey, values: Record<string, string | number> = {}): string {
  const row = STOREFRONT_COPY[locale];
  const text = row[COPY_KEYS.indexOf(key)];
  if (!text) throw new Error(`Missing storefront copy: ${locale}.${key}`);
  const number = new Intl.NumberFormat(localeMeta(locale).html);
  return text.replace(/\{(\w+)\}/g, (match, name: string) => {
    const value = values[name];
    return value === undefined ? match : typeof value === 'number' ? number.format(value) : value;
  });
}
