/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HikayeRouteImport } from './routes/hikaye'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OdemeRouteImport } from './routes/odeme'
import { Route as PaketRouteImport } from './routes/paket'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SepetRouteImport } from './routes/sepet'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TeslimatRouteImport } from './routes/teslimat'
import { Route as TicariRouteImport } from './routes/ticari'
import { Route as UyumRouteImport } from './routes/uyum'
import { Route as YasalRouteImport } from './routes/yasal'
import { Route as OdemeBasariliRouteImport } from './routes/odeme.basarili'
import { Route as OdemeIptalRouteImport } from './routes/odeme.iptal'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as SiparisIdRouteImport } from './routes/siparis.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HikayeRoute = HikayeRouteImport.update({
  id: '/hikaye',
  path: '/hikaye',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeRoute = OdemeRouteImport.update({
  id: '/odeme',
  path: '/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketRoute = PaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SepetRoute = SepetRouteImport.update({
  id: '/sepet',
  path: '/sepet',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TeslimatRoute = TeslimatRouteImport.update({
  id: '/teslimat',
  path: '/teslimat',
  getParentRoute: () => rootRouteImport,
} as any)
const TicariRoute = TicariRouteImport.update({
  id: '/ticari',
  path: '/ticari',
  getParentRoute: () => rootRouteImport,
} as any)
const UyumRoute = UyumRouteImport.update({
  id: '/uyum',
  path: '/uyum',
  getParentRoute: () => rootRouteImport,
} as any)
const YasalRoute = YasalRouteImport.update({
  id: '/yasal',
  path: '/yasal',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeBasariliRoute = OdemeBasariliRouteImport.update({
  id: '/basarili',
  path: '/basarili',
  getParentRoute: () => OdemeRoute,
} as any)
const OdemeIptalRoute = OdemeIptalRouteImport.update({
  id: '/iptal',
  path: '/iptal',
  getParentRoute: () => OdemeRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ShopRoute,
} as any)
const SiparisIdRoute = SiparisIdRouteImport.update({
  id: '/siparis/$id',
  path: '/siparis/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hikaye': typeof HikayeRoute
  '/iletisim': typeof IletisimRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/odeme': typeof OdemeRouteWithChildren
  '/paket': typeof PaketRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sepet': typeof SepetRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teslimat': typeof TeslimatRoute
  '/ticari': typeof TicariRoute
  '/uyum': typeof UyumRoute
  '/yasal': typeof YasalRoute
  '/odeme/basarili': typeof OdemeBasariliRoute
  '/odeme/iptal': typeof OdemeIptalRoute
  '/p/$slug': typeof PSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/siparis/$id': typeof SiparisIdRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hikaye': typeof HikayeRoute
  '/iletisim': typeof IletisimRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/odeme': typeof OdemeRouteWithChildren
  '/paket': typeof PaketRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sepet': typeof SepetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teslimat': typeof TeslimatRoute
  '/ticari': typeof TicariRoute
  '/uyum': typeof UyumRoute
  '/yasal': typeof YasalRoute
  '/odeme/basarili': typeof OdemeBasariliRoute
  '/odeme/iptal': typeof OdemeIptalRoute
  '/p/$slug': typeof PSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/siparis/$id': typeof SiparisIdRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hikaye': typeof HikayeRoute
  '/iletisim': typeof IletisimRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/odeme': typeof OdemeRouteWithChildren
  '/paket': typeof PaketRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sepet': typeof SepetRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teslimat': typeof TeslimatRoute
  '/ticari': typeof TicariRoute
  '/uyum': typeof UyumRoute
  '/yasal': typeof YasalRoute
  '/odeme/basarili': typeof OdemeBasariliRoute
  '/odeme/iptal': typeof OdemeIptalRoute
  '/p/$slug': typeof PSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/siparis/$id': typeof SiparisIdRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hikaye'
    | '/iletisim'
    | '/llms.txt'
    | '/odeme'
    | '/paket'
    | '/robots.txt'
    | '/sepet'
    | '/shop'
    | '/sitemap.xml'
    | '/teslimat'
    | '/ticari'
    | '/uyum'
    | '/yasal'
    | '/odeme/basarili'
    | '/odeme/iptal'
    | '/p/$slug'
    | '/shop/$category'
    | '/siparis/$id'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hikaye'
    | '/iletisim'
    | '/llms.txt'
    | '/odeme'
    | '/paket'
    | '/robots.txt'
    | '/sepet'
    | '/sitemap.xml'
    | '/teslimat'
    | '/ticari'
    | '/uyum'
    | '/yasal'
    | '/odeme/basarili'
    | '/odeme/iptal'
    | '/p/$slug'
    | '/shop/$category'
    | '/siparis/$id'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/hikaye'
    | '/iletisim'
    | '/llms.txt'
    | '/odeme'
    | '/paket'
    | '/robots.txt'
    | '/sepet'
    | '/shop'
    | '/sitemap.xml'
    | '/teslimat'
    | '/ticari'
    | '/uyum'
    | '/yasal'
    | '/odeme/basarili'
    | '/odeme/iptal'
    | '/p/$slug'
    | '/shop/$category'
    | '/siparis/$id'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HikayeRoute: typeof HikayeRoute
  IletisimRoute: typeof IletisimRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OdemeRoute: typeof OdemeRouteWithChildren
  PaketRoute: typeof PaketRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SepetRoute: typeof SepetRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeslimatRoute: typeof TeslimatRoute
  TicariRoute: typeof TicariRoute
  UyumRoute: typeof UyumRoute
  YasalRoute: typeof YasalRoute
  PSlugRoute: typeof PSlugRoute
  SiparisIdRoute: typeof SiparisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hikaye': {
      id: '/hikaye'
      path: '/hikaye'
      fullPath: '/hikaye'
      preLoaderRoute: typeof HikayeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme': {
      id: '/odeme'
      path: '/odeme'
      fullPath: '/odeme'
      preLoaderRoute: typeof OdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paket': {
      id: '/paket'
      path: '/paket'
      fullPath: '/paket'
      preLoaderRoute: typeof PaketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sepet': {
      id: '/sepet'
      path: '/sepet'
      fullPath: '/sepet'
      preLoaderRoute: typeof SepetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teslimat': {
      id: '/teslimat'
      path: '/teslimat'
      fullPath: '/teslimat'
      preLoaderRoute: typeof TeslimatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticari': {
      id: '/ticari'
      path: '/ticari'
      fullPath: '/ticari'
      preLoaderRoute: typeof TicariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uyum': {
      id: '/uyum'
      path: '/uyum'
      fullPath: '/uyum'
      preLoaderRoute: typeof UyumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yasal': {
      id: '/yasal'
      path: '/yasal'
      fullPath: '/yasal'
      preLoaderRoute: typeof YasalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme/basarili': {
      id: '/odeme/basarili'
      path: '/basarili'
      fullPath: '/odeme/basarili'
      preLoaderRoute: typeof OdemeBasariliRouteImport
      parentRoute: typeof OdemeRoute
    }
    '/odeme/iptal': {
      id: '/odeme/iptal'
      path: '/iptal'
      fullPath: '/odeme/iptal'
      preLoaderRoute: typeof OdemeIptalRouteImport
      parentRoute: typeof OdemeRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/siparis/$id': {
      id: '/siparis/$id'
      path: '/siparis/$id'
      fullPath: '/siparis/$id'
      preLoaderRoute: typeof SiparisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OdemeRouteChildren {
  OdemeBasariliRoute: typeof OdemeBasariliRoute
  OdemeIptalRoute: typeof OdemeIptalRoute
}

const OdemeRouteChildren: OdemeRouteChildren = {
  OdemeBasariliRoute: OdemeBasariliRoute,
  OdemeIptalRoute: OdemeIptalRoute,
}

const OdemeRouteWithChildren = OdemeRoute._addFileChildren(OdemeRouteChildren)

interface ShopRouteChildren {
  ShopCategoryRoute: typeof ShopCategoryRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCategoryRoute: ShopCategoryRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HikayeRoute: HikayeRoute,
  IletisimRoute: IletisimRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OdemeRoute: OdemeRouteWithChildren,
  PaketRoute: PaketRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SepetRoute: SepetRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeslimatRoute: TeslimatRoute,
  TicariRoute: TicariRoute,
  UyumRoute: UyumRoute,
  YasalRoute: YasalRoute,
  PSlugRoute: PSlugRoute,
  SiparisIdRoute: SiparisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
